<?xml version="1.0"?>
<package format="3">
  <name>lm_writer</name><version>0.1.0</version>
  <description>Writer robot high-level nodes (Raspberry Pi).</description>
  <maintainer email="todo@todo">team</maintainer><license>MIT</license>
  <exec_depend>rclpy</exec_depend><exec_depend>lm_interfaces</exec_depend>
  <exec_depend>nav_msgs</exec_depend><exec_depend>sensor_msgs</exec_depend><exec_depend>geometry_msgs</exec_depend>
  <exec_depend>tf2_ros</exec_depend><exec_depend>micro_ros_agent</exec_depend>
  <export><build_type>ament_python</build_type></export>
</package>
