#!/usr/bin/env python3
"""schema.yaml -> C header, Python module, ROS 2 .msg files, micro-ROS converters, test vectors.
One schema, three languages: STM/ESP (C), Pi/ONA/CP/sim (Python), ROS 2 (msg)."""
import json, struct, yaml, pathlib

ROOT = pathlib.Path(__file__).parent
S = yaml.safe_load(open(ROOT / "schema.yaml"))
GEN = ROOT / "generated"
T = {  # schema type -> (C type, struct fmt, ROS type, py type)
    "u8": ("uint8_t", "B", "uint8", "int"), "i8": ("int8_t", "b", "int8", "int"),
    "u16": ("uint16_t", "H", "uint16", "int"), "i16": ("int16_t", "h", "int16", "int"),
    "u32": ("uint32_t", "I", "uint32", "int"), "i32": ("int32_t", "i", "int32", "int"),
    "f32": ("float", "f", "float32", "float"),
}

def fields(name):
    m = S["messages"][name]; out = []
    if "include" in m: out += fields(m["include"])
    for f, spec in m["fields"].items():
        t, _, enum = str(spec).partition("/"); out.append((f, t, enum or None))
    return out

def snake(n): return "".join("_" + c.lower() if c.isupper() else c for c in n).lstrip("_")

def gen_c():
    L = ["/* AUTO-GENERATED by contracts/codegen.py — DO NOT EDIT */", "#pragma once", "#include <stdint.h>", "",
         "#ifdef __cplusplus   /* firmware main.cpp includes this too */", "#define LM_STATIC_ASSERT static_assert",
         "#else", "#define LM_STATIC_ASSERT _Static_assert", "#endif", ""]
    for e, vals in S["enums"].items():
        L += [f"typedef enum {{"] + [f"    LM_{snake(e).upper()}_{k} = {v}," for k, v in vals.items()] + [f"}} lm_{snake(e)}_t;", ""]
    for n, m in S["messages"].items():
        L.append(f"#define LM_MSG_{snake(n).upper()} 0x{m['id']:02X}")
    L.append("")
    for n, m in S["messages"].items():
        if m.get("doc"): L.append(f"/* {m['doc']} */")
        L.append("typedef struct __attribute__((packed)) {")
        for f, t, enum in fields(n):
            L.append(f"    {T[t][0]:9s} {f};" + (f"  /* {enum} */" if enum else ""))
        size = struct.calcsize("<" + "".join(T[t][1] for _, t, _ in fields(n)))
        L += [f"}} lm_{snake(n)}_t;", f"LM_STATIC_ASSERT(sizeof(lm_{snake(n)}_t) == {size}, \"{n} size mismatch\");", ""]
    (GEN / "c").mkdir(parents=True, exist_ok=True)
    (GEN / "c" / "lm_msgs.h").write_text("\n".join(L) + "\n")

def gen_py():
    L = ['"""AUTO-GENERATED by contracts/codegen.py — DO NOT EDIT"""', "import struct", "from dataclasses import dataclass, astuple", "from enum import IntEnum", ""]
    for e, vals in S["enums"].items():
        L += [f"class {e}(IntEnum):"] + [f"    {k} = {v}" for k, v in vals.items()] + [""]
    for n, m in S["messages"].items():
        fs = fields(n); fmt = "<" + "".join(T[t][1] for _, t, _ in fs)
        L += ["@dataclass", f"class {n}:"]
        if m.get("doc"): L.append(f'    """{m["doc"]}"""')
        L += [f"    {f}: {T[t][3]} = 0" for f, t, _ in fs]
        L += [f"    ID = 0x{m['id']:02X}", f"    FMT = {fmt!r}", f"    SIZE = struct.calcsize(FMT)",
              f"    def pack(self) -> bytes: return struct.pack(self.FMT, *astuple(self))",
              f"    @classmethod", f"    def unpack(cls, b: bytes): return cls(*struct.unpack(cls.FMT, b))", ""]
    L.append("BY_ID = {" + ", ".join(f"0x{m['id']:02X}: {n}" for n, m in S["messages"].items()) + "}")
    (GEN / "py").mkdir(parents=True, exist_ok=True)
    (GEN / "py" / "lm_msgs.py").write_text("\n".join(L) + "\n")

def gen_ros():
    d = GEN / "ros" / "msg"; d.mkdir(parents=True, exist_ok=True)
    for old in d.glob("*.msg"): old.unlink()   # drop .msg of messages removed from the schema
    for n, m in S["messages"].items():
        L = ["# AUTO-GENERATED by contracts/codegen.py — DO NOT EDIT"]
        if m.get("doc"): L.append(f"# {m['doc']}")
        L += [f"{T[t][2]} {f}" + (f"  # {enum}" if enum else "") for f, t, enum in fields(n)]
        (d / f"{n}.msg").write_text("\n".join(L) + "\n")

def gen_uros():
    """Packed wire struct <-> micro-ROS (rosidl C, not packed) converters, field by field — never memcpy.
    Each pair only compiles if the rosidl header of that message was included before this one."""
    L = ["/* AUTO-GENERATED by contracts/codegen.py — DO NOT EDIT */",
         "/* Include the lm_interfaces/msg/<name>.h headers you need BEFORE this header; each pair is guarded by its rosidl include guard. */",
         "#pragma once", '#include "lm_msgs.h"', ""]
    for n in S["messages"]:
        s, fs = snake(n), fields(n); ros = f"lm_interfaces__msg__{n}"
        L += [f"#ifdef LM_INTERFACES__MSG__{s.upper()}_H_",
              f"static inline void lm_ros_from_{s}({ros} *dst, const lm_{s}_t *src) {{"]
        L += [f"    dst->{f} = src->{f};" for f, _, _ in fs]
        L += ["}", f"static inline void lm_{s}_from_ros(lm_{s}_t *dst, const {ros} *src) {{"]
        L += [f"    dst->{f} = src->{f};" for f, _, _ in fs]
        L += ["}", f"#endif /* LM_INTERFACES__MSG__{s.upper()}_H_ */", ""]
    (GEN / "c").mkdir(parents=True, exist_ok=True)
    (GEN / "c" / "lm_uros_conv.h").write_text("\n".join(L) + "\n")

def gen_vectors():
    import sys; sys.path.insert(0, str(GEN / "py")); sys.path.insert(0, str(ROOT.parent / "libs"))
    import importlib, lm_msgs; importlib.reload(lm_msgs)
    from lm_core.link import encode
    v = {"SensorDet": lm_msgs.SensorDet(type=1, detected=1, value=61.5, conf=200, t_ms=123456),
         "BeaconPayload": lm_msgs.BeaconPayload(id=3, what=3, prio=4, conf=180, dir_deg=270, dist_cm=412,
                                                prev_id=2, next_id=255, age_s=17, version=1, flags=2,
                                                phase_ms=1250)}
    (GEN / "test_vectors.json").write_text(json.dumps({k: encode(m.ID, m.pack()).hex() for k, m in v.items()}, indent=1))

if __name__ == "__main__":
    gen_c(); gen_py(); gen_ros(); gen_uros(); gen_vectors(); print("generated ->", GEN)
